server.port=8081

# PostgreSQL
spring.datasource.url=jdbc:postgresql://postgres:5432/social_db
spring.datasource.username=postgres
spring.datasource.password=27042004
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# File upload configuration
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=20MB
file.upload-dir=uploads

# 🟢 ĐÃ VÁ LỖI CỔ CHAI (REMOVED BOTTLENECKS)
# Mở rộng kết nối DB cho phù hợp
spring.datasource.hikari.maximum-pool-size=30
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.connection-timeout=10000

# Tăng cường số lượng Request Thread của Web Server
server.tomcat.threads.max=200
server.tomcat.accept-count=100
